spring:
  data:
     mongodb:
          uri: mongodb://root:root@localhost:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true
          database: gerenciador-tarefas
server:
  port: 9090

